compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

injectEnvironmentFiles:
  - .env.yarn?
  - .env.local?

nodeLinker: node-modules

progressBarStyle: jack

supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current

yarnPath: .yarn/releases/yarn-4.1.1.cjs
